// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID              string                 `json:"id"`
	VideoID         string                 `json:"videoId"`
	Content         string                 `json:"content"`
	TableOfContents []*TableOfContentsItem `json:"tableOfContents"`
}

type Mutation struct {
}

type Query struct {
}

type TableOfContentsItem struct {
	Title     string  `json:"title"`
	Timestamp float64 `json:"timestamp"`
}

type Video struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	URL   string `json:"url"`
}
