// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID        string `json:"id"`
	VideoName string `json:"videoName"`
	Content   string `json:"content"`
	Title     string `json:"title"`
}

type Mutation struct {
}

type Query struct {
}

